sudo: required

language: generic

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

script:
  - docker build -t slack_silence_test -f dev.dockerfile .
  - docker run --rm slack_silence_test mix test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker build -t sophilabs/slack-silence:latest .
      echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      docker push sophilabs/slack-silence:latest
    fi